// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Health, HealthTableId } from "./tables/Health.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
