// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Avatar, AvatarData, AvatarTableId } from "./tables/Avatar.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Health, HealthTableId } from "./tables/Health.sol";
import { Stamina, StaminaTableId } from "./tables/Stamina.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
