// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Character, CharacterData, CharacterTableId } from "./tables/Character.sol";
import { Attributes, AttributesData, AttributesTableId } from "./tables/Attributes.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Health, HealthTableId } from "./tables/Health.sol";
import { Stamina, StaminaTableId } from "./tables/Stamina.sol";
import { Intent, IntentData, IntentTableId } from "./tables/Intent.sol";
import { Action, ActionData, ActionTableId } from "./tables/Action.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
