// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IBattleSystem {
  function intend() external;

  function attack(bytes32 target) external;

  function counterAttack(bytes32 target) external;
}
