// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IHealthSystem {
  function refill() external returns (uint32);

  function revive() external returns (uint32);

  function kill() external returns (uint32);

  function heal(uint32 addVal) external returns (uint32);

  function hurt(uint32 redVal) external returns (uint32);

  function isDead() external view returns (bool);

  function isAlive() external view returns (bool);
}
