// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPlayerSystem {
  function createPlayer(string memory name, string memory charType) external;

  function createOpponent(string memory name, string memory charType) external;

  function spawnPlayer(int32 x, int32 y) external;
}
