// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IStaminaSystem {
  function refillStamina() external returns (uint32);

  function drain() external returns (uint32);

  function rest(uint32 addVal) external returns (uint32);

  function exhaust(uint32 redVal) external returns (uint32);

  function isExhausted() external view returns (bool);

  function isFresh() external view returns (bool);

  function hasSufficientStamina(uint32 intentStaminaCost) external returns (bool);
}
