// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IBattleSystem } from "./IBattleSystem.sol";
import { IHealthSystem } from "./IHealthSystem.sol";
import { IIncrementSystem } from "./IIncrementSystem.sol";
import { IInitializationSystem } from "./IInitializationSystem.sol";
import { IMovementSystem } from "./IMovementSystem.sol";
import { IPlayerSystem } from "./IPlayerSystem.sol";
import { IStaminaSystem } from "./IStaminaSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is
  IBaseWorld,
  IBattleSystem,
  IHealthSystem,
  IIncrementSystem,
  IInitializationSystem,
  IMovementSystem,
  IPlayerSystem,
  IStaminaSystem
{

}
